package com.altipeak.safewalk;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

/**
 * Authentication Response
 * 
 * @since v1.1.10
 */
public class AuthenticationResponse {

    private final AuthenticationCode code;
    private final String transactionId;
    private final String username;
    private final String replyMessage;
    
    private final int httpCode;
    private final String detail;
    
    private final Map<String, List<String>> errors;
    
    private static final String SEPARATOR = " | ";

    public enum AuthenticationCode {
        ACCESS_ALLOWED,
        ACCESS_CHALLENGE,
        ACCESS_DENIED;
    }
    
    /*protected*/ AuthenticationResponse(int httpCode
                                , AuthenticationCode code
                                , String transactionId
                                , String username
                                , String replyMessage
                                , String detail) {
        this.code = code;
        this.transactionId = transactionId;
        this.username = username;
        this.replyMessage = replyMessage;
        this.httpCode = httpCode;
        this.detail = detail;
        this.errors = Collections.emptyMap();
    }
    
    /*protected*/ AuthenticationResponse(int httpCode, Map<String, List<String>> errors){
        this.code = null;
        this.transactionId = null;
        this.username = null;
        this.replyMessage = null;
        this.httpCode = httpCode;
        this.detail = null;
        this.errors = errors;
    }
    
    // ************************************
    // * Public Methods
    // ************************************
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.valueOf(this.httpCode)).append(SEPARATOR);
        if ( this.code != null ) sb.append(this.code).append(SEPARATOR);
        if ( this.transactionId != null ) sb.append(this.transactionId).append(SEPARATOR);
        if ( this.username != null ) sb.append(this.username).append(SEPARATOR);
        if ( this.replyMessage != null ) sb.append(this.replyMessage).append(SEPARATOR);
        if ( this.detail != null ) sb.append(this.detail).append(SEPARATOR);
        
        for (Entry<String, List<String>> errors : this.errors.entrySet()) {
            sb.append(errors.getKey()).append(" [");
            for (String error : errors.getValue()) {
                sb.append(error).append(", ");
            }
            sb.append("]").append(SEPARATOR);
        }
        
        return sb.toString();
    }

    /**
     * Useful when {@link AuthenticationResponse#getHttpCode()} is 400
     * 
     * @since v1.1.10
     * @return a {@link Map} with the fields that contains errors. Example : 
     * <pre>
     * {
     *   "password": [
     *       "This field is required."
     *   ]
     * }
     * </pre>
     * 
     */
    public Map<String, List<String>> getErrors() {
        return errors;
    }

    /**
     * @since v1.1.10
     * @return the authentication result 
     */
    public AuthenticationCode getCode() {
        return code;
    }

    /**
     * @since v1.1.10
     * @return the transactionId generated by the server (or passed by parameter). Useful to link transactions between the client and Safewalk.
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * @since v1.1.10
     * @return the authenticated username if {@link AuthenticationResponse#getCode()} is {@link AuthenticationCode#ACCESS_ALLOWED} or {@link AuthenticationCode#ACCESS_CHALLENGE} otherwise is null
     */
    public String getUsername() {
        return username;
    }

    /**
     * @since v1.1.10
     * @return the replay message from the server (Only available in English) if {@link AuthenticationResponse#getHttpCode()} is 401, 200 or 500 (Can't connect to LDAP) otherwise is null
     */
    public String getReplyMessage() {
        return replyMessage;
    }

    /**
     * @since v1.1.10
     * @return 
     * <ul>
     *   <li> 200 if {@link AuthenticationCode#ACCESS_ALLOWED}
     *   <li> 401 if {@link AuthenticationCode#ACCESS_CHALLENGE} or {@link AuthenticationCode#ACCESS_DENIED}. Also if the OAUTH2 access token is not valid. 
     *   <li> 500 if can't contact LDAP
     * </ul>
     */
    public int getHttpCode() {
        return httpCode;
    }

    
    /**
     * @since v1.1.10
     * @return A detail where it explains why the OAUTH2 access token is not valid. Only available if {@link AuthenticationResponse#getHttpCode()} is 401 and {@link AuthenticationResponse#getCode()} is null.
     */
    public String getDetail() {
        return detail;
    }
    
}
